title: Modelo de Predicciones para Counter-Strike 2
description: Proyecto de Ciencia de Datos para la creación de un modelo de predicciones de partidos profesionales de CS2.
baseurl:
url: https://jimenez73.github.io/Proyecto-Semestral-Grupo-13/

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/